//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adres()
        {
            this.DokumentSprzedazy = new HashSet<DokumentSprzedazy>();
            this.Kontrahent = new HashSet<Kontrahent>();
            this.Pracownik = new HashSet<Pracownik>();
            this.TypKontrahenta = new HashSet<TypKontrahenta>();
        }
    
        public int IdAdresu { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string NrDomu { get; set; }
        public string NrLokalu { get; set; }
        public string KodPocztowy { get; set; }
        public string Powiat { get; set; }
        public Nullable<int> IdKraju { get; set; }
        public Nullable<int> IdWojewodzctwa { get; set; }
        public string Gmina { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Kraj Kraj { get; set; }
        public virtual Wojewodzctwo Wojewodzctwo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumentSprzedazy> DokumentSprzedazy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrahent> Kontrahent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypKontrahenta> TypKontrahenta { get; set; }
    }
}
