//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSAktualnosc
    {
        public int IdAktualnosci { get; set; }
        public string LinkTytul { get; set; }
        public string Tytul { get; set; }
        public string Tresc { get; set; }
        public int Pozycja { get; set; }
    }
}
