//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanePersonalne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanePersonalne()
        {
            this.DokumentSprzedazy = new HashSet<DokumentSprzedazy>();
            this.Kontrahent = new HashSet<Kontrahent>();
            this.Pracownik = new HashSet<Pracownik>();
            this.TypKontrahenta = new HashSet<TypKontrahenta>();
            this.Uzytkownik = new HashSet<Uzytkownik>();
        }
    
        public int IdDanePersonalne { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public string ImieDane { get; set; }
        public string DrugieImie { get; set; }
        public string NazwiskoDane { get; set; }
        public string NazwiskoRodoweMatki { get; set; }
        public string ImieOjca { get; set; }
        public string ImieMatki { get; set; }
        public string NrPaszportu { get; set; }
        public string PESELDane { get; set; }
        public Nullable<System.DateTime> DataUrodzenia { get; set; }
        public string NIPDane { get; set; }
        public string REGONDane { get; set; }
        public string TelefonDane { get; set; }
        public string EmailDane { get; set; }
        public string NazwaDane { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string MiejscowoscDane { get; set; }
        public string UlicaDane { get; set; }
        public string NrDomuDane { get; set; }
        public string Kraj { get; set; }
        public string Wojewodztwo { get; set; }
        public string Plec { get; set; }
        public string UwagiDane { get; set; }
        public string RachunekNrDane { get; set; }
        public Nullable<decimal> RabatDane { get; set; }
        public string BankDane { get; set; }
        public string NrLokaluDane { get; set; }
        public string KodPocztowyDane { get; set; }
        public string KodDane { get; set; }
        public string WalutaDane { get; set; }
        public string FormaPlatnosciDane { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumentSprzedazy> DokumentSprzedazy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrahent> Kontrahent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypKontrahenta> TypKontrahenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzytkownik> Uzytkownik { get; set; }
    }
}
