//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentSprzedazy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DokumentSprzedazy()
        {
            this.DokumentSprzedazyTowar = new HashSet<DokumentSprzedazyTowar>();
            this.Reklamacje = new HashSet<Reklamacje>();
            this.ZakupTowaru = new HashSet<ZakupTowaru>();
        }
    
        public int IdDokumentuSprzedazy { get; set; }
        public string NumerDokumentu { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<int> IdAdres { get; set; }
        public Nullable<int> IdDaneParsonalne { get; set; }
        public Nullable<int> IdRabatu { get; set; }
        public Nullable<int> IdSposobuPlatnosci { get; set; }
        public Nullable<int> IdRodzajuDokumentow { get; set; }
        public Nullable<int> IdPlatnosci { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<int> PozycjaDokumentu { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual DanePersonalne DanePersonalne { get; set; }
        public virtual Dodatkowe Dodatkowe { get; set; }
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual Platnosci Platnosci { get; set; }
        public virtual Rabat Rabat { get; set; }
        public virtual RodzajDokumentu RodzajDokumentu { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumentSprzedazyTowar> DokumentSprzedazyTowar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacje> Reklamacje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakupTowaru> ZakupTowaru { get; set; }
    }
}
