//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentSprzedazyTowar
    {
        public int Id { get; set; }
        public int IdDokumentSprzedazy { get; set; }
        public int IdTowar { get; set; }
        public int Ilosc { get; set; }
    
        public virtual DokumentSprzedazy DokumentSprzedazy { get; set; }
        public virtual Towar Towar { get; set; }
    }
}
