//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahent()
        {
            this.DokumentSprzedazy = new HashSet<DokumentSprzedazy>();
            this.Reklamacje = new HashSet<Reklamacje>();
            this.ZakupTowaru = new HashSet<ZakupTowaru>();
        }
    
        public int IdKontrahenta { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public Nullable<int> IdTypuKontrahenta { get; set; }
        public Nullable<int> IdRodzajuDokumentow { get; set; }
        public Nullable<int> IdPlatnosci { get; set; }
        public Nullable<int> IdRabatu { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<int> IdDanePersonalne { get; set; }
        public Nullable<int> IdPlci { get; set; }
        public Nullable<int> IdBanku { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual DanePersonalne DanePersonalne { get; set; }
        public virtual Dodatkowe Dodatkowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumentSprzedazy> DokumentSprzedazy { get; set; }
        public virtual Platnosci Platnosci { get; set; }
        public virtual Plec Plec { get; set; }
        public virtual Rabat Rabat { get; set; }
        public virtual RodzajDokumentu RodzajDokumentu { get; set; }
        public virtual TypKontrahenta TypKontrahenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacje> Reklamacje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakupTowaru> ZakupTowaru { get; set; }
    }
}
