//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanUrlopu
    {
        public int IdPlanuUrlospu { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> IdUrlopu { get; set; }
        public Nullable<int> IdRodzajWolnego { get; set; }
        public Nullable<System.DateTime> DataRozpoczeciaUrlopu { get; set; }
        public Nullable<System.DateTime> DataZakonczeniaUrlopu { get; set; }
        public Nullable<decimal> Dni { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual RodzajWolnego RodzajWolnego { get; set; }
        public virtual Urlop Urlop { get; set; }
    }
}
