//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatnoscPrzelewem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlatnoscPrzelewem()
        {
            this.Platnosci = new HashSet<Platnosci>();
        }
    
        public int IdPlatnosciPrzelewem { get; set; }
        public Nullable<int> IdPlatnoscOdKontrahenta { get; set; }
        public Nullable<int> IdPlatnoscDoDostawcy { get; set; }
        public Nullable<int> IdBanku { get; set; }
        public Nullable<System.DateTime> DataPaltnosci { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual PlatnoscDoDostawcy PlatnoscDoDostawcy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosci> Platnosci { get; set; }
        public virtual PlatnoscOdKontrahenta PlatnoscOdKontrahenta { get; set; }
    }
}
