//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platnosci()
        {
            this.DokumentSprzedazy = new HashSet<DokumentSprzedazy>();
            this.Kontrahent = new HashSet<Kontrahent>();
            this.ZakupTowaru = new HashSet<ZakupTowaru>();
        }
    
        public int IdPlatnosci { get; set; }
        public Nullable<decimal> Waluta { get; set; }
        public string NrKontaBankowego { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public Nullable<decimal> Brutto { get; set; }
        public Nullable<decimal> WartoscZamowienia { get; set; }
        public Nullable<decimal> RejestrDluznikow { get; set; }
        public Nullable<int> IdPlatnosciOdKontrahenta { get; set; }
        public Nullable<int> IdPlatnosciDoDostawcy { get; set; }
        public Nullable<int> IdPlatnosciPrzelewem { get; set; }
        public Nullable<int> IdPlatnosciKarta { get; set; }
        public Nullable<int> IdPlatnosciGotowka { get; set; }
        public Nullable<int> IdPlatnosciBlikiem { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumentSprzedazy> DokumentSprzedazy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrahent> Kontrahent { get; set; }
        public virtual PlatnoscBlikiem PlatnoscBlikiem { get; set; }
        public virtual PlatnoscDoDostawcy PlatnoscDoDostawcy { get; set; }
        public virtual PlatnoscGotowka PlatnoscGotowka { get; set; }
        public virtual PlatnoscKarta PlatnoscKarta { get; set; }
        public virtual PlatnoscOdKontrahenta PlatnoscOdKontrahenta { get; set; }
        public virtual PlatnoscPrzelewem PlatnoscPrzelewem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakupTowaru> ZakupTowaru { get; set; }
    }
}
