//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamacje
    {
        public int IdReklamacji { get; set; }
        public Nullable<int> IdTowaru { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<int> IdZadanieReklamujacego { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<System.DateTime> DataZakupu { get; set; }
        public Nullable<System.DateTime> DataPowstaniaWady { get; set; }
        public Nullable<System.DateTime> DataGwarancjiDo { get; set; }
        public Nullable<int> IdDokumentuSprzedazy { get; set; }
        public Nullable<int> IdStatusu { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string ImieR { get; set; }
        public string NazwiskoR { get; set; }
        public string MiejscowoscR { get; set; }
        public string KodPocztowyR { get; set; }
        public string UlicaR { get; set; }
        public string NrLokaluR { get; set; }
        public string NrDomuR { get; set; }
        public string PESELR { get; set; }
        public string TowaryR { get; set; }
        public string DostawcaR { get; set; }
        public string IloscR { get; set; }
        public string JednostkaR { get; set; }
        public string DokumentR { get; set; }
        public string OpisR { get; set; }
        public string TelefonR { get; set; }
        public string EmailR { get; set; }
        public string ZadaniaReklamujacegoR { get; set; }
    
        public virtual Dodatkowe Dodatkowe { get; set; }
        public virtual DokumentSprzedazy DokumentSprzedazy { get; set; }
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual Status Status { get; set; }
        public virtual Towar Towar { get; set; }
        public virtual ZadanieReklamujacego ZadanieReklamujacego { get; set; }
    }
}
