//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SklepTowar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SklepTowar()
        {
            this.SklepElementKoszyka = new HashSet<SklepElementKoszyka>();
        }
    
        public int IdTowaru { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena { get; set; }
        public string Foto { get; set; }
        public string Opis { get; set; }
        public int IdRodzaju { get; set; }
        public bool Promocja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SklepElementKoszyka> SklepElementKoszyka { get; set; }
    }
}
