//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortowanieUzytkownikow
    {
        public int SortujUzytkownikow { get; set; }
        public string NazwaSortowaniaUzytkownikow { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    }
}
