//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzczegolyTowaru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SzczegolyTowaru()
        {
            this.ZakupTowaru = new HashSet<ZakupTowaru>();
        }
    
        public int IdSzczegolyTowaru { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<int> IdKategoriiTowaru { get; set; }
        public string OkresGwarancji { get; set; }
        public Nullable<int> IdMarki { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Dodatkowe Dodatkowe { get; set; }
        public virtual KategoriaTowaru KategoriaTowaru { get; set; }
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakupTowaru> ZakupTowaru { get; set; }
    }
}
