//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towar()
        {
            this.DokumentSprzedazyTowar = new HashSet<DokumentSprzedazyTowar>();
            this.Reklamacje = new HashSet<Reklamacje>();
            this.ZakupTowaru = new HashSet<ZakupTowaru>();
        }
    
        public int IdTowaru { get; set; }
        public Nullable<decimal> CenaNetto { get; set; }
        public Nullable<decimal> CenaBrutto { get; set; }
        public string JednostkaMiary { get; set; }
        public Nullable<decimal> Marza { get; set; }
        public Nullable<decimal> StawkaVatZakupu { get; set; }
        public Nullable<decimal> StawkaVatSprzedazy { get; set; }
        public string Kod { get; set; }
        public string KodEan { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
        public Nullable<int> IdProducenta { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<int> IdRodzajuDokumentow { get; set; }
        public Nullable<int> idTypKontrahenta { get; set; }
        public Nullable<int> IdKategoriiTowaru { get; set; }
        public Nullable<int> IdMarki { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string MarkaT { get; set; }
        public string KategoriaTowaruT { get; set; }
        public string ProducentT { get; set; }
    
        public virtual Dodatkowe Dodatkowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumentSprzedazyTowar> DokumentSprzedazyTowar { get; set; }
        public virtual KategoriaTowaru KategoriaTowaru { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Producent Producent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacje> Reklamacje { get; set; }
        public virtual RodzajDokumentu RodzajDokumentu { get; set; }
        public virtual TypKontrahenta TypKontrahenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakupTowaru> ZakupTowaru { get; set; }
    }
}
