//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypKontrahenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypKontrahenta()
        {
            this.Kontrahent = new HashSet<Kontrahent>();
            this.Towar = new HashSet<Towar>();
        }
    
        public int IdTypuKontrahenta { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public Nullable<int> IdDanePersonalne { get; set; }
        public Nullable<int> IdDodatkowe { get; set; }
        public Nullable<int> IdRodzajuDokumentow { get; set; }
        public string Odbiorca { get; set; }
        public string Dostawca { get; set; }
        public string Zablokowany { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual DanePersonalne DanePersonalne { get; set; }
        public virtual Dodatkowe Dodatkowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrahent> Kontrahent { get; set; }
        public virtual RodzajDokumentu RodzajDokumentu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Towar> Towar { get; set; }
    }
}
