//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urlop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urlop()
        {
            this.PlanUrlopu = new HashSet<PlanUrlopu>();
            this.Pracownik = new HashSet<Pracownik>();
            this.Zatrudnienie = new HashSet<Zatrudnienie>();
        }
    
        public int IdUrlopu { get; set; }
        public Nullable<decimal> WykorzystanoU { get; set; }
        public Nullable<decimal> DodatkoweDniUrlopu { get; set; }
        public Nullable<int> IdRodzajWolnego { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<System.DateTime> DataRozpUrlopuU { get; set; }
        public string RodzajUrlopuU { get; set; }
        public string RodzajUmowyU { get; set; }
        public string WymiarEtatuU { get; set; }
        public Nullable<decimal> LimitUrlopuU { get; set; }
        public string NazwaPracownikU { get; set; }
        public string ImieU { get; set; }
        public string DrugieImieU { get; set; }
        public string NazwiskoU { get; set; }
        public string NazwiskoRodMatU { get; set; }
        public string ImieOjcaU { get; set; }
        public string ImieMatkiU { get; set; }
        public string MiejscowoscU { get; set; }
        public Nullable<System.DateTime> DataUrodzeniaU { get; set; }
        public string KrajU { get; set; }
        public string PowiatU { get; set; }
        public string GminaU { get; set; }
        public string NrPaszportuU { get; set; }
        public string UlicaU { get; set; }
        public string NrDomuU { get; set; }
        public string NrLokaluU { get; set; }
        public string TelefonU { get; set; }
        public string EmailU { get; set; }
        public string WojewodzctwoU { get; set; }
        public Nullable<System.DateTime> DataZakonczeniaUrlopu { get; set; }
        public string StanowiskoU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanUrlopu> PlanUrlopu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
        public virtual RodzajWolnego RodzajWolnego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zatrudnienie> Zatrudnienie { get; set; }
    }
}
