//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownik()
        {
            this.Pracownik = new HashSet<Pracownik>();
        }
    
        public int IdUzytkownika { get; set; }
        public Nullable<int> IdDanePersonalne { get; set; }
        public Nullable<int> IdStanowiskoPracownika { get; set; }
        public Nullable<int> IdDaneLogowania { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual DaneLogowania DaneLogowania { get; set; }
        public virtual DanePersonalne DanePersonalne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
        public virtual StanowiskoPracownika StanowiskoPracownika { get; set; }
    }
}
