//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wynagrodzenie
    {
        public int IdWynagrodzenia { get; set; }
        public Nullable<decimal> Stawka { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> IdRodzajuUmowy { get; set; }
        public Nullable<int> IdRodzajZatrudnienia { get; set; }
        public Nullable<int> IdStanowiskoPracownika { get; set; }
        public Nullable<int> IdZatrudnienia { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual RodzajUmowy RodzajUmowy { get; set; }
        public virtual RodzajZatrudnienia RodzajZatrudnienia { get; set; }
        public virtual StanowiskoPracownika StanowiskoPracownika { get; set; }
        public virtual Zatrudnienie Zatrudnienie { get; set; }
    }
}
