//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zatrudnienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zatrudnienie()
        {
            this.Pracownik = new HashSet<Pracownik>();
            this.Wynagrodzenie = new HashSet<Wynagrodzenie>();
        }
    
        public int IdZatrudnienia { get; set; }
        public Nullable<System.DateTime> DataZatrudnienia { get; set; }
        public Nullable<System.DateTime> DataRoczpoczeciaPracy { get; set; }
        public Nullable<System.DateTime> DataZwolnienia { get; set; }
        public Nullable<int> IdRodzajuUmowy { get; set; }
        public string WymiarEtatu { get; set; }
        public Nullable<int> IdRodzajZatrudnienia { get; set; }
        public Nullable<int> IdStanowiskoPracownika { get; set; }
        public Nullable<int> IdUrlop { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
        public virtual RodzajUmowy RodzajUmowy { get; set; }
        public virtual RodzajZatrudnienia RodzajZatrudnienia { get; set; }
        public virtual StanowiskoPracownika StanowiskoPracownika { get; set; }
        public virtual Urlop Urlop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wynagrodzenie> Wynagrodzenie { get; set; }
    }
}
